db.alerts_msg.insert({
    "_id":"en_US",
    "LowFuel_push":"Low fuel detected. Current fuel level is [$.Data.fuelLevel]%.",
    "LowFuel_sms":"Low fuel detected. Current fuel level is [$.Data.fuelLevel]%.",
    "LowFuel_email":"Low fuel detected. Current fuel level is [$.Data.fuelLevel]%.",
    "LowFuel_browser":"Low fuel detected. Current fuel level is [$.Data.fuelLevel]%.",
    "GeoFence_push_out":"Your vehicle is outside of the set boundary.",
    "GeoFence_push_in":"Your vehicle is back inside the set boundary.",
    "GeoFence_sms_out":"Your vehicle is outside of the set boundary.",
    "GeoFence_sms_in":"Your vehicle is back inside the set boundary.",
    "GeoFence_mail_out":"Your vehicle is outside of the set boundary.", 
    "GeoFence_mail_in":"Your vehicle is back inside the set boundary.",
    "GeoFence_browser_out":"Your vehicle is outside of the set boundary.",
    "GeoFence_browser_in":"Your vehicle is back inside the set boundary.",
    "Collision_push":"Vehicle crash detected at location http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude]. Your emergency contacts have been notified.",
    "Collision_sms":"Vehicle crash detected at location http://maps.google.com/maps?q=loc:$[$.Data.latitude],[$.Data.longitude]. Your emergency contacts have been notified.",
    "Collision_email":"Vehicle crash detected at location http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude]. Your emergency contacts have been notified.",
    "Collision_browser":"Vehicle crash detected at location http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude]. Your emergency contacts have been notified.",
    "DTCStored_push_set":"A problem has been detected with your vehicle. Identified as:${DTC_LIST}.",
    "DTCStored_sms_set":"A problem has been detected with your vehicle. Identified as:${DTC_LIST}.",
    "DTCStored_email_set":"A problem has been detected with your vehicle. Identified as:${DTC_LIST}.",
    "DTCStored_browser_set":"A problem has been detected with your vehicle. Identified as:${DTC_LIST}.",
    "DTCStored_push_cleared":"One or more problems  (${DTC_LIST}) have been fixed.",
    "DTCStored_sms_cleared":"One or more problems  (${DTC_LIST}) have been fixed.",
    "DTCStored_email_cleared":"One or more problems  (${DTC_LIST}) have been fixed.",
    "DTCStored_browser_cleared":"One or more problems  (${DTC_LIST}) have been fixed.",
    "OverSpeeding_push":"Your vehicle has gone over the speed limit.",
    "OverSpeeding_sms":"Your vehicle has gone over the speed limit.",
    "OverSpeeding_email":"Your vehicle has gone over the speed limit.",
    "OverSpeeding_browser":"Your vehicle has gone over the speed limit.",
    "GeoFence_valet_push_in":"Your vehicle is back inside the valet boundary.",
    "GeoFence_valet_push_out":"Your vehicle has gone outside of the valet boundary.",
    "GeoFence_valet_sms_in":"Your vehicle is back inside the valet boundary.",
    "GeoFence_valet_sms_out":"Your vehicle has gone outside of the valet boundary.",
    "GeoFence_valet_email_in":"Your vehicle is back inside the valet boundary.",
    "GeoFence_valet_email_out":"Your vehicle has gone outside of the valet boundary.",
    "GeoFence_valet_browser_in":"Your vehicle is back inside the valet boundary.",
    "GeoFence_valet_browser_out":"Your vehicle has gone outside of the valet boundary.",
    "GeoFence_generic_push_out":"Your vehicle is outside of the [$.Data.name] boundary.",
    "GeoFence_generic_push_in":"Your vehicle is back inside the [$.Data.name] boundary.",
    "GeoFence_generic_sms_out":"Your vehicle is outside of the [$.Data.name] boundary.",
    "GeoFence_generic_sms_in":"Your vehicle is back inside the [$.Data.name] boundary.",
    "GeoFence_generic_email_out":"Your vehicle is outside of the [$.Data.name] boundary.",
    "GeoFence_generic_email_in":"Your vehicle is back inside the [$.Data.name] boundary.",
    "GeoFence_generic_browser_out":"Your vehicle is outside of the [$.Data.name] boundary.",
    "GeoFence_generic_browser_in":"Your vehicle is back inside the [$.Data.name] boundary.",
    "CurfewViolation_push":"Your vehicle is being used past curfew.",
    "CurfewViolation_sms":"Your vehicle is being used past curfew.",
    "CurfewViolation_email":"Your vehicle is being used past curfew.",
    "CurfewViolation_browser":"Your vehicle is being used past curfew.",
    "CurfewViolation_push_time":"Your vehicle is being used past [$.Data.curfewStartTime] curfew.",
    "CurfewViolation_sms_time":"Your vehicle is being used past [$.Data.curfewStartTime] curfew.",
    "CurfewViolation_email_time":"Your vehicle is being used past [$.Data.curfewStartTime] curfew.",
    "CurfewViolation_browser_time":"Your vehicle is being used past [$.Data.curfewStartTime] curfew.",
    "Idle_push":"Your vehicle has been idling for [$.Data.duration] minutes.",
    "Idle_sms":"Your vehicle has been idling for [$.Data.duration] minutes.",
    "Idle_email":"Your vehicle has been idling for [$.Data.duration] minutes.",
    "Idle_browser":"Your vehicle has been idling for [$.Data.duration] minutes.",
    "NonIdle_push":"Your vehicle has started to move after idling for [$.Data.duration] minutes.",
    "NonIdle_sms":"Your vehicle has started to move after idling for [$.Data.duration] minutes.",
    "NonIdle_email":"Your vehicle has started to move after idling for [$.Data.duration] minutes.",
    "NonIdle_browser":"Your vehicle has started to move after idling for [$.Data.duration] minutes.",
    "Tow_push":"Your vehicle is being towed.Current location is http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude].",
    "Tow_sms":"Your vehicle is being towed.Current location is http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude].",
    "Tow_email":"Your vehicle is being towed.Current location is http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude].",
    "Tow_browser":"Your vehicle is being towed.Current location is http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude].",
    "GeoFence_privatelocation_push_out":"Your vehicle is back outside of the [$.Data.name] boundary.",
    "GeoFence_privatelocation_sms_out":"Your vehicle is back outside of the [$.Data.name]boundary.",
    "GeoFence_privatelocation_email_out":"Your vehicle is back outside of the [$.Data.name] boundary.",
    "GeoFence_privatelocation_browser_out":"Your vehicle is back outside of the [$.Data.name] boundary.",
    "GeoFence_privatelocation_push_in":"Your vehicle has entered the [$.Data.name] boundary.",
    "GeoFence_privatelocation_sms_in":"Your vehicle has entered the [$.Data.name] boundary.",
    "GeoFence_privatelocation_email_in":"Your vehicle has entered the [$.Data.name] boundary.",
    "GeoFence_privatelocation_browser_in":"Your vehicle has entered the [$.Data.name] boundary.",
    "DongleStatus_push_attached":"The dongle has been reattached to your vehicle.",
    "DongleStatus_sms_attached":"The dongle has been reattached to your vehicle.",
    "DongleStatus_email_attached":"The dongle has been reattached to your vehicle.",
    "DongleStatus_browser_attached":"The dongle has been reattached to your vehicle.",
    "DongleStatus_push_detached":"The dongle has been disconnected from your vehicle.",
    "DongleStatus_sms_detached":"The dongle has been disconnected from your vehicle.",
    "DongleStatus_email_detached":"The dongle has been disconnected from your vehicle.",
    "DongleStatus_browser_detached":"The dongle has been disconnected from your vehicle.",  
    "DongleDetached_push":"The dongle has been disconnected from your vehicle.",
    "DongleDetached_sms":"The dongle has been disconnected from your vehicle.",
    "DongleDetached_email":"The dongle has been disconnected from your vehicle.",
    "DongleDetached_browser":"The dongle has been disconnected from your vehicle.",
    "DocumentExpiry_push":"Your [$.Data.DocumentName] document will be expired in [$.Data.ExpiryDate] day(s).",
    "DocumentExpiry_sms":"Your [$.Data.DocumentName] document will be expired in [$.Data.ExpiryDate] day(s).",
    "DocumentExpiry_email":"Your [$.Data.DocumentName] document will be expired in [$.Data.ExpiryDate] day(s).",
    "DocumentExpiry_browser":"Your [$.Data.DocumentName] document will be expired in [$.Data.ExpiryDate] day(s).",
    "ServiceReminder_ReminderEngine_push":"Your service is due on [$.Data.reminderDate]. Please visit a service station.",
    "ServiceReminder_ReminderEngine_sms":"Your service is due on [$.Data.reminderDate]. Please visit a service station.",
    "ServiceReminder_ReminderEngine_email":"Your service is due on [$.Data.reminderDate]. Please visit a service station.",
    "ServiceReminder_ReminderEngine_browser":"Your service is due on [$.Data.reminderDate]. Please visit a service station.",
    "ServiceReminder_OdometerReading_push":"Your service is due based on odometer reading. Please visit a service station.",
    "ServiceReminder_OdometerReading_sms":"Your service is due based on odometer reading. Please visit a service station.",
    "ServiceReminder_OdometerReading_email":"Your service is due based on odometer reading. Please visit a service station.",
    "ServiceReminder_OdometerReading_browser":"Your service is due based on odometer reading. Please visit a service station.",
    "PinGenerated_email":"Verification Code for registering your device with IMEI [$.Data.imei] is [$.Data.pin]. This Code is valid for [$.Data.duration].",
    "PinGenerated_sms":"Verification Code for registering your device with IMEI [$.Data.imei] is [$.Data.pin]. This Code is valid for [$.Data.duration].",
    "PinGenerated_push":"Verification Code for registering your device with IMEI [$.Data.imei] is [$.Data.pin]. This Code is valid for [$.Data.duration].",
    "PinGenerated_browser":"Verification Code for registering your device with IMEI [$.Data.imei] is [$.Data.pin]. This Code is valid for [$.Data.duration].",
    "Disturbance_email":"Disturbance detected at location http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude].",
    "Disturbance_sms":"Disturbance detected at location http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude].",
    "Disturbance_push":"Disturbance detected at location http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude].",
    "Disturbance_browser":"Disturbance detected at location http://maps.google.com/maps?q=loc:[$.Data.latitude],[$.Data.longitude].",
    "Activation_push":"Congratulations!  Your device is activated and ready to use!",
    "Activation_sms":"Congratulations!  Your device is activated and ready to use!",
    "Activation_email":"Congratulations!  Your device is activated and ready to use!",
    "Activation_browser":"Congratulations!  Your device is activated and ready to use!",
    "FirmwareDownloaded_push":"Your device software is updating.",
    "FirmwareDownloaded_sms":"Your device software is updating.",
    "FirmwareDownloaded_email":"Your device software is updating.",
    "FirmwareDownloaded_browser":"Your device software is updating.",
    "FirmwareUpgraded_push":"Software update for your device is complete",
    "FirmwareUpgraded_sms":"Software update for your device is complete",
    "FirmwareUpgraded_email":"Software update for your device is complete",
    "FirmwareUpgraded_browser":"Software update for your device is complete",
    "MMY_email":"Your vehicle's Make, Model, Year and Vehicle Name could not be determined. Please set now.",
    "MMY_sms":"Your vehicle's Make, Model, Year and Vehicle Name could not be determined. Please set now.",
    "MMY_push":"Your vehicle's Make, Model, Year and Vehicle Name could not be determined. Please set now.",
    "MMY_browser":"Your vehicle's Make, Model, Year and Vehicle Name could not be determined. Please set now."

})
db.alerts.insert({
            "pdid":"HUX12345",
            "alertType":"Collision",
            "timestamp" : 1486100143502,
            "createDts" : ISODate("2017-02-03T04:43:00.814Z"),
            "payload" : {
                "EventID" : "Collision",
                "Data" : {
                    "VehicleSpeedUnit" : "kmpl",
                    "DummyKey" : "DummyValue",
                    "latitude" : "15.92458",
                    "longitude" : "79.852421",
                    "VehicleSpeed" : "44"
                },
                "Version" : "1.0",
                "BenchMode" : 1,
                "Timestamp" : 1481724868055,
                "Timezone" : 330,
                "pdid" : "HUX12345"
            },
            "channelResponses" : [
                {
                    "channelType" : "MOBILE_APP_PUSH",
                    "alertEventData" : {
                        "default" : "Vehicle crash detected at location http://maps.google.com/maps?q=loc:15.92458,79.852421. Your emergency contacts have been notified."
                    },
                    "userID" : "mahendra_ch",
                    "alertsObject" : {
                        "EventID" : "Collision",
                        "Data" : {
                            "VehicleSpeedUnit" : "kmpl",
                            "DummyKey" : "DummyValue",
                            "latitude" : "15.92458",
                            "longitude" : "79.852421",
                            "VehicleSpeed" : "44"
                        },
                        "Version" : "1.0",
                        "BenchMode" : 1,
                        "Timestamp" : 1481724868055,
                        "Timezone" : 330,
                        "pdid" : "HUX12345"
                    },
                    "processedTime" : "1507030254812",
                    "fcmResponse" : "{\"multicast_id\":7490766205233681315,\"success\":0,\"failure\":1,\"canonical_ids\":0,\"results\":[{\"error\":\"NotRegistered\"}]}"
                },
                {
                    "channelType" : "SMS",
                    "alertEventData" : {
                        "default" : "Vehicle crash detected at location http://maps.google.com/maps?q=loc:15.92458,79.852421. Your emergency contacts have been notified."
                    },
                    "userID" : "mahendra_ch",
                    "alertsObject" : {
                        "EventID" : "Collision",
                        "Data" : {
                            "VehicleSpeedUnit" : "kmpl",
                            "DummyKey" : "DummyValue",
                            "latitude" : "15.92458",
                            "longitude" : "79.852421",
                            "VehicleSpeed" : "44"
                        },
                        "Version" : "1.0",
                        "BenchMode" : 1,
                        "Timestamp" : 1481724868055,
                        "Timezone" : 330,
                        "pdid" : "HUX12345"
                    },
                    "pdid" : "HUX12345",
                    "processedTime" : "1507030254920",
                    "topics" : [
                        {
                            "topicARN" : "arn:aws:sns:us-east-1:222260823685:mahendra_ch_sms",
                            "publishTrackingID" : "2f39f73d-4b71-5f91-941f-a5703c5f77a9",
                            "subscriptions" : [ ]
                        }
                    ]
                },
                {
                    "channelType" : "EMAIL",
                    "alertEventData" : {
                        "default" : "Vehicle crash detected at location http://maps.google.com/maps?q=loc:15.92458,79.852421. Your emergency contacts have been notified."
                    },
                    "userID" : "mahendra_ch",
                    "alertsObject" : {
                        "EventID" : "Collision",
                        "Data" : {
                            "VehicleSpeedUnit" : "kmpl",
                            "DummyKey" : "DummyValue",
                            "latitude" : "15.92458",
                            "longitude" : "79.852421",
                            "VehicleSpeed" : "44"
                        },
                        "Version" : "1.0",
                        "BenchMode" : 1,
                        "Timestamp" : 1481724868055,
                        "Timezone" : 330,
                        "pdid" : "HUX12345"
                    },
                    "processedTime" : "1507030254986",
                    "messageId" : "0100015ee200c5f6-9746cd09-1e41-4dcf-a104-45a42b4d875f-000000"
                }
            ]
     })
